CFLAGS += -std=c99 -O -Wall -Wextra -pedantic -Wold-style-declaration -Wmissing-prototypes -Wno-unused-parameter
CLIBS  += -lX11 -lXinerama -lXcomposite -lXft -lGL -lpthread $(shell pkg-config --cflags --libs xft)
PREFIX ?= /usr
BINDIR ?= $(PREFIX)/bin
CC     ?= gcc

all: sbtab

config.h:
	cp config.def.h config.h

sbtab: sbtab.c sbtab.h config.h Makefile
	$(CC) -O3 $(CFLAGS) -o sbtab sbtab.c $(CLIBS) $(LDFLAGS)

install: all
	install -Dm755 sbtab $(DESTDIR)$(BINDIR)/sbtab

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/sbtab

clean:
	rm -f sbtab *.o config.h

.PHONY: all install uninstall clean
